# Generated by Django 5.2.7 on 2025-11-07 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_alter_departmentmodel_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_app.positionmodel', verbose_name='position'),
        ),
    ]
