# Generated by Django 5.2.7 on 2025-11-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_employeemodel_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentmodel',
            name='manager',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='department',
            field=models.ManyToManyField(to='employee_app.departmentmodel', verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='image',
            field=models.ImageField(upload_to='image', verbose_name='image'),
        ),
    ]
