# Generated by Django 5.2.7 on 2025-11-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_remove_departmentmodel_manager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentmodel',
            old_name='name',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='positionmodel',
            old_name='name',
            new_name='position_name',
        ),
        migrations.RenameField(
            model_name='statusmodel',
            old_name='name',
            new_name='status_name',
        ),
    ]
