# Generated by Django 5.2.7 on 2025-11-07 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0005_rename_name_departmentmodel_department_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='department',
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_app.employeemodel', verbose_name='manager'),
        ),
    ]
