# Generated by Django 5.2.7 on 2025-11-07 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0006_remove_employeemodel_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmodel',
            name='department_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='departmentmodel',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_app.employeemodel', verbose_name='manager'),
        ),
        migrations.AlterField(
            model_name='positionmodel',
            name='position_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='statusmodel',
            name='status_name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Status'),
        ),
    ]
