# Generated by Django 5.2.7 on 2025-11-07 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0007_alter_departmentmodel_department_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentmodel',
            name='manager',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='department',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_app.departmentmodel', verbose_name='department'),
        ),
    ]
