# Generated by Django 5.2.7 on 2025-11-07 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0008_remove_departmentmodel_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmodel',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_app.employeemodel', verbose_name='manager'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_app.departmentmodel', verbose_name='department'),
        ),
    ]
