# Generated by Django 5.2.7 on 2025-11-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0009_departmentmodel_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='image', verbose_name='image'),
        ),
    ]
